- Dropdown menu:
  Admin: Assign walkers, Client tools, User tools (+ walkers)
  Walkers: Home/assigned dogs, update my info, logout.

- Home page:
  Admin: Date, Assign walkers, Dogs walked this week? Notes for review.
  Walker: Date, today's assigned dogs. Total dogs walked (this year?)?

- Assign walkers page:
  Columns: left is searchable walkers, right is searchable dogs. Top panel indicated assigned dogs for confirmation?

- Assigned Dogs page:
  Card listing of assigned dogs, with Date/time of walk scheduled.

- Assigned dogs details:
  Options here for add note/photo.
